db.url=jdbc:postgresql://localhost:5432/postgres
db.username=grinchak
db.password=zdnegbrt232
db.driver= org.postgresql.Driver
hikari.connectionTimeout=20000
hikari.minimumIdle=1
hikari.maximumPoolSize=10
hikari.idleTimeout=300000
hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
hibernate.show_sql=true
hibernate.format_sql=true
hibernate.hbm2ddl.auto=update